### ISSUE TITLE
DS_Store and Mantis files included in cell table generation

### ISSUE THREAD

**Issue by rdj71** [angelolab/Nimbus-Inference#10]
### Report

Using a mac to run nimbus.predict_fovs(), I ran into an error that .DS_Store files could not be found, and ran into another error about .mantisDB files not found. I ran a script to remove all .DS_Store files that fixed the issue, and also ran a script to remove all .mantisDB files. After doing so, the cell_table was generated, but if trying to regenerate the cell_table, there is another .DS_Store file still in the directory that I needed to remove again.

<img width="1153" alt="nimbus_error" src="https://github.com/angelolab/Nimbus-Inference/assets/168581669/9e2247ff-5922-4585-8b5c-74351ec143db">

**Comment by JLrumberger** [comment]
Hi @rdj71,

thanks for raising this issue. I'll fix it ASAP.

Best,
Lorenz

**Comment by JLrumberger** [comment]
Hi @rdj71,

could it be that your problem can be fixed by just excluding the '.DS_Store' and '.mantisDB' paths from `fov_paths` after this line in the inference notebook: `fov_paths = [os.path.join(tiff_dir, fov_name) for fov_name in fov_names]`? If not, can lay out the folder structure? I was assuming something like this, where would the folders causing the problem be in this structure?
```
|-- base_dir
|   |-- image_data
|   |   |-- fov_1
|   |   |-- fov_2
|   |-- segmentation
|   |   |-- deepcell_output
|   |   |   |-- fov_1_whole_cell.tiff
|   |   |   |-- fov_2_whole_cell.tiff
|   |-- nimbus_output
```
